### ISSUE TITLE
Fails to restore build on ubuntu-latest (22.04.1 LTS)

### ISSUE THREAD

**Issue by JackNoordhuis** [pmmp/setup-php-action#62]
It looks like libzip5 isn't available for 22.04.1 as it was published for 20.x.x to fix/workaround something by pinning the libzip version installed by libzip5 to an older version than libzip4: https://github.com/actions/runner-images/issues/1084#issue-642250128

```
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libzip5
Error: The process '/home/runner/work/_actions/pmmp/setup-php-action/7e0f5f0a95e9d45d1d5fab0e1ee7555fa3b04339/install-dependencies.sh' failed with exit code 100
```

I'll just stick to using ubuntu 20.x for now but this should be addressed so the action can be more widely used.

**Comment by dktapps** [comment]
22.04 is generally unsupported right now. There are compatibility issues with the system version of OpenSSL as well.

**Comment by dktapps** [comment]
Fixed by using prebuilts from pmmp/PHP-Binaries directly (ea71138ee1f044a5e037253cca8bf3d3a5ccb5e2), at the expense of not being able to specify a patch version (but I don't think anyone really cared about that anyway).
